# Generated by Django 4.2.1 on 2023-05-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='title_setting',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='title_setting',
        ),
    ]
