# Generated by Django 4.2.1 on 2023-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_aboutimage_question_partner_link_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_main',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
